# Copyright (c) 2024-2025 Ziqi Fan
# SPDX-License-Identifier: Apache-2.0
# test51
atom/homie_vel_gym:
  model_name: "test201_est_vel.onnx"
  num_one_step_observations: 79 # 76 79
  num_history: 6 
  num_observations: 474 # 456 474
  clip_obs: 100.0
  clip_actions: 100.0
  rl_kp: [154.88, 100.37, 52.16, 115.49, 21.83, 21.83,
          154.88, 100.37, 52.16, 115.49, 21.83, 21.83]
  rl_kd: [16.43, 10.65, 5.53, 12.25, 2.32, 2.32,
          16.43, 10.65, 5.53, 12.25, 2.32, 2.32]
  num_of_policy_dofs: 27
  action_dim: 12 
  action_scale: [0.45, 0.77, 0.67, 0.78, 1.49, 1.49,
                0.45, 0.77, 0.67, 0.78, 1.49, 1.49]
  default_dof_pos: [-0.1, 0.0, 0.0, 0.3, -0.2, 0.0,
                    -0.1, 0.0, 0.0, 0.3, -0.2, 0.0,
                    0.0, 
                    0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
                    0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
  torque_limits: [280.0, 308.0, 140.0, 360.0, 130.0, 130.0,
                  280.0, 308.0, 140.0, 360.0, 130.0, 130.0,
                  250.0,
                  56.0, 36.0, 36.0, 36.0, 18.6, 18.6, 18.6,
                  56.0, 36.0, 36.0, 36.0, 18.6, 18.6, 18.6,
                  12.0, 12.0]
  lin_vel_scale: 2.0
  ang_vel_scale: 0.5
  dof_pos_scale: 1.0
  dof_vel_scale: 0.05
  commands_scale: [2.0, 2.0, 0.5]
  joint_mapping: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28]
