# Copyright (c) 2024-2025 Ziqi Fan
# SPDX-License-Identifier: Apache-2.0
# test51
atom/humanoid_gym:
  model_name: "humanoid-gym-76.onnx"
  num_one_step_observations: 47 # 76 79
  num_history: 15
  num_observations: 705 # 456 474
  clip_obs: 18.0
  clip_actions: 18.0
#   rl_kp: [100, 95, 50, 110, 30, 30,
#           100, 95, 50, 110, 30, 30,]
  rl_kp: [100, 95, 50, 110, 50, 50,
          100, 95, 50, 110, 50, 50,]
#   rl_kp: [100, 95, 90, 110, 75, 75,
#           100, 95, 90, 110, 75, 75,]
#   rl_kp: [100, 95, 90, 110, 50, 50,
#           100, 95, 90, 110, 50, 50,]

#   rl_kd: [3.5, 2.5, 1.5, 3.5, 0.2, 0.2,
#           3.5, 2.5, 1.5, 3.5, 0.2, 0.2,]
#   rl_kd: [3.5, 2.5, 2.5, 3.5, 2, 2,
#           3.5, 2.5, 2.5, 3.5, 2, 2,]
#   rl_kd: [3.5, 2.5, 2.5, 3.5, 0.3, 0.3,
#           3.5, 2.5, 2.5, 3.5, 0.3, 0.3,]
  rl_kd: [3.5, 2.5, 1.5, 3.5, 0.3, 0.3,
          3.5, 2.5, 1.5, 3.5, 0.3, 0.3,]
  num_of_policy_dofs: 12
  action_dim: 12 
  action_scale: [0.5, 0.5, 0.5, 0.5, 0.5, 0.5,
                0.5, 0.5, 0.5, 0.5, 0.5, 0.5,]
  default_dof_pos: [-0.2, 0.0, 0.0, 0.4, -0.2, 0.0,
                    -0.2, 0.0, 0.0, 0.4, -0.2, 0.0]
  torque_limits: [280.0, 308.0, 140.0, 360.0, 130.0, 130.0,
                  280.0, 308.0, 140.0, 360.0, 130.0, 130.0,
                  250.0,
                  56.0, 36.0, 36.0, 36.0, 18.6, 18.6, 18.6,
                  56.0, 36.0, 36.0, 36.0, 18.6, 18.6, 18.6,
                  12.0, 12.0]
  lin_vel_scale: 2.0
  ang_vel_scale: 1.0
  dof_pos_scale: 1.0
  dof_vel_scale: 0.05
  commands_scale: [2.0, 2.0, 1.0]
  joint_mapping: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28]
